services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    restart: always

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://user:password@db/inventory_db
      - SECRET_KEY=your-super-secret-key-change-it
      - DEBUG=False
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    # --- ЗМІНА ТУТ: Ми видалили секцію 'volumes' ---
    # Тепер контейнер повністю самодостатній
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
